### Create Provider
POST http://localhost:8080/api/providers
Content-Type: application/json

{
  "name": "Interactive Investor"
}

### Get Providers
GET http://localhost:8080/api/providers
Accept: application/json

### Create Pot
POST http://localhost:8080/api/pots
Content-Type: application/json

{
  "provider": { "id": 202 },
  "name": "OLM Old",
  "currency": "GBP",
  "status": "active",
  "planNumber": "K1615471000",
  "schemeNumber": "J44580"
}

### Get Pots
GET http://localhost:8080/api/pots
Accept: application/json

### Get Pot By Id
GET http://localhost:8080/api/pots/103
Accept: application/json

### Snapshot - Opening
POST http://localhost:8080/api/snapshots
Content-Type: application/json

{
  "pot": { "id": 103 },
  "date": "2024-01-01",
  "balance": 100000.0
}

### Transaction - Contribution
POST http://localhost:8080/api/transactions
Content-Type: application/json

{
  "pot": { "id": 102 },
  "date": "2025-02-01",
  "type": "contribution",
  "amount": 8000.0
}

### Transaction - Rebate
POST http://localhost:8080/api/transactions
Content-Type: application/json

{
  "pot": { "id": 102 },
  "date": "2025-02-21",
  "type": "rebate",
  "amount": 2000.0
}

